config/routes.rb
Rails.application.routes.draw do
  root "submissions#index"
  resources :submissions
  resources :challenges
  devise_for :users
  get '/submissions/:id/test', to: 'submissions#test'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/challenge.rb
class Challenge < ApplicationRecord
  mount_uploader :challenge, ChallengeUploader
  mount_uploader :test, TestUploader
end

app/models/submission.rb
class Submission < ApplicationRecord
  mount_uploader :submission, SubmissionUploader
  belongs_to :challenge
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/challenges_controller.rb
class ChallengesController < ApplicationController
  before_action :set_challenge, only: [:show, :edit, :update, :destroy]

  # GET /challenges
  # GET /challenges.json
  def index
    @challenges = Challenge.all
  end

  # GET /challenges/1
  # GET /challenges/1.json
  def show
  end

  # GET /challenges/new
  def new
    @challenge = Challenge.new
  end

  # GET /challenges/1/edit
  def edit
  end

  # POST /challenges
  # POST /challenges.json
  def create
    @challenge = Challenge.new(challenge_params)

    respond_to do |format|
      if @challenge.save
        format.html { redirect_to @challenge, notice: 'Challenge was successfully created.' }
        format.json { render :show, status: :created, location: @challenge }
      else
        format.html { render :new }
        format.json { render json: @challenge.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /challenges/1
  # PATCH/PUT /challenges/1.json
  def update
    respond_to do |format|
      if @challenge.update(challenge_params)
        format.html { redirect_to @challenge, notice: 'Challenge was successfully updated.' }
        format.json { render :show, status: :ok, location: @challenge }
      else
        format.html { render :edit }
        format.json { render json: @challenge.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /challenges/1
  # DELETE /challenges/1.json
  def destroy
    @challenge.destroy
    respond_to do |format|
      format.html { redirect_to challenges_url, notice: 'Challenge was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_challenge
      @challenge = Challenge.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def challenge_params
      params.require(:challenge).permit!
    end
end

app/controllers/submissions_controller.rb
class SubmissionsController < ApplicationController
  before_action :set_submission, only: [:show, :edit, :test, :update, :destroy]

  # GET /submissions
  # GET /submissions.json
  def index
    @submissions = Submission.all
  end

  # GET /submissions/1
  # GET /submissions/1.json
  def show
  end

  # GET /submissions/new
  def new
    @submission = Submission.new
  end

  # GET /submissions/1/edit
  def edit
  end

  # GET /submissions/1/test
  def test

    # Is it a zip?
    if File.extname(@submission.submission_url) == '.zip'
      # Extract
      Zip::File.open("./public#{@submission.submission_url}") do |zip|
        zip.each do |file|
          file.extract("ruby_docker/lib/#{file.name}")
        end
      end
    else
      # Not a zip, copy single solution file
      FileUtils.cp("./public#{@submission.submission_url}", "ruby_docker/lib/#{@submission.challenge.challenge_identifier}")
    end

    # Copy tests from the original challenge
    FileUtils.cp("./public#{@submission.challenge.test_url}", "ruby_docker/tests/tests.rb")

    # Build container, run tests
    system('cd ruby_docker && docker build -t ruby-challenge -f Dockerfile.production . && docker build -t ruby-challenge-test -f Dockerfile.test .')
    @test_output = `docker run --rm ruby-challenge-test`
    @submission.passed = @test_output.include? '100% passed'
    @submission.save

    # Clean up
    system('rm -rf ruby_docker/lib/*')
    system('rm -rf ruby_docker/tests/*')
  end

  # POST /submissions
  # POST /submissions.json
  def create
    @submission = Submission.new(submission_params)

    respond_to do |format|
      if @submission.save
        format.html { redirect_to "/submissions/#{@submission.id}/test" }
        format.json { render :show, status: :created, location: @submission }
      else
        format.html { render :new }
        format.json { render json: @submission.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /submissions/1
  # PATCH/PUT /submissions/1.json
  def update
    respond_to do |format|
      if @submission.update(submission_params)
        format.html { redirect_to @submission, notice: 'Submission was successfully updated.' }
        format.json { render :show, status: :ok, location: @submission }
      else
        format.html { render :edit }
        format.json { render json: @submission.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /submissions/1
  # DELETE /submissions/1.json
  def destroy
    @submission.destroy
    respond_to do |format|
      format.html { redirect_to submissions_url, notice: 'Submission was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_submission
      @submission = Submission.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def submission_params
      params.require(:submission).permit(:challenge_id, :submission)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/challenges_helper.rb
module ChallengesHelper
end

app/helpers/submissions_helper.rb
module SubmissionsHelper
end

app/views/challenges/_form.html.erb
<%= form_with(model: challenge, local: true, :multipart => true) do |form| %>
  <% if challenge.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(challenge.errors.count, "error") %> prohibited this challenge from being saved:</h2>

      <ul>
      <% challenge.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :challenge_title %>
  </div>

  <div class="field">
    <%= form.label :challenge %>
    <%= form.file_field :challenge, id: :challenge_challenge %>
  </div>

  <div class="field">
    <%= form.label :test %>
    <%= form.file_field :test, id: :challenge_test %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/challenges/edit.html.erb
<h1>Editing Challenge</h1>

<%= render 'form', challenge: @challenge %>

<%= link_to 'Show', @challenge %> |
<%= link_to 'Back', challenges_path %>

app/views/challenges/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Challenges</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @challenges.each do |challenge| %>
      <tr>
        <td><%= challenge.title %></td>
        <td><%= link_to 'Show', challenge %></td>
        <td><%= link_to 'Edit', edit_challenge_path(challenge) %></td>
        <td><%= link_to 'Destroy', challenge, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Challenge', new_challenge_path %>

app/views/challenges/new.html.erb
<h1>New Challenge</h1>

<%= render 'form', challenge: @challenge %>

<%= link_to 'Back', challenges_path %>

app/views/challenges/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @challenge.title %>
</p>

<p>
  <strong>Challenge:</strong>
  <%= @challenge.challenge_url %>
</p>

<p>
  <strong>Test:</strong>
  <%= @challenge.test_url %>
</p>

<%= link_to 'Edit', edit_challenge_path(@challenge) %> |
<%= link_to 'Back', challenges_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ChallengerDocker</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav>
    <% if user_signed_in? %>
      <%= link_to "Challenges (Admin)", challenges_path %> |
      <%= link_to "Submissions", submissions_path %> |
      Logged in as: <%= current_user.email %>
      <%= link_to "Log out", destroy_user_session_path, :method=>'delete' %>
    <% else %>
      <%= link_to "login", new_user_session_path %>
    <% end %>
    </nav>

    <hr>

    <%= yield %>

  </body>
</html>

app/views/submissions/_form.html.erb
<%= form_with(model: submission, local: true) do |form| %>
  <% if submission.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(submission.errors.count, "error") %> prohibited this submission from being saved:</h2>

      <ul>
      <% submission.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :challenge_id %>
    <%= form.collection_select :challenge_id, Challenge.all, :id, :title %>
  </div>

  <div class="field">
    <%= form.label :submission %>
    <%= form.file_field :submission, id: :submission_submission %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/submissions/edit.html.erb
<h1>Editing Submission</h1>

<%= render 'form', submission: @submission %>

<%= link_to 'Show', @submission %> |
<%= link_to 'Back', submissions_path %>

app/views/submissions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Submissions</h1>

<table>
  <thead>
    <tr>
      <th>Challenge</th>
      <th>Submission</th>
      <th>Result</th>
    </tr>
  </thead>

  <tbody>
    <% @submissions.each do |submission| %>
      <tr>
        <td><%= submission.challenge.title %></td>
        <td><%= submission.submission %></td>
        <td><%= submission.passed ? 'passed' : 'failed' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Submission', new_submission_path %>

app/views/submissions/new.html.erb
<h1>New Submission</h1>

<%= render 'form', submission: @submission %>

<%= link_to 'Back', submissions_path %>

app/views/submissions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Challenge:</strong>
  <%= @submission.challenge.title %>
</p>

<p>
  <strong>Submission:</strong>
  <%= @submission.submission %>
</p>

<%= link_to 'Edit', edit_submission_path(@submission) %> |
<%= link_to 'Back', submissions_path %>

app/views/submissions/test.html.erb
<%= @submission.passed ? '✅' : '' %> <%= @submission.challenge.title %>

<pre class="<%= @submission.passed ? 'success' : 'failure' %>">
<%= @test_output %>
</pre>